# Generated by Django 3.2 on 2023-02-06 12:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Допустимые значние 1-10'), django.core.validators.MaxValueValidator(10, message='Допустимые значние 1-10')]),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(default=datetime.datetime(2023, 2, 6, 17, 26, 22, 843550), validators=[django.core.validators.MaxValueValidator(2023)], verbose_name='Дата релиза'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
